config/routes.rb
Rails.application.routes.draw do
  resources :columns
  resources :boards
  resources :projects
  resources :assignees
  resources :milestones
  resources :tasks
  resources :filters

  root to: 'welcome#index'

  mount ActionCable.server => '/cable'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  get 'users/:id', to: 'users#show', as: :user
  patch 'users/:id', to: 'users#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignee.rb
class Assignee < ApplicationRecord
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :columns
end

app/models/column.rb
class Column < ApplicationRecord
  default_scope { order(:position) }

  belongs_to :board

  has_many :tasks

  validates :name, presence: true
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :column

  Filter.inheritance_column = '_type'

  TYPES = ['namespace', 'project', 'title']
end

app/models/milestone.rb
class Milestone < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :milestone, optional: true
  belongs_to :assignee, optional: true
  belongs_to :project, optional: true
  belongs_to :column, optional: true

  self.inheritance_column = :_type_disabled

  serialize :labels

  default_scope { order(:position) }

  def in_progress?
    !!['Testing', 'In Progress'].include?(self.column.name)
  rescue
    false
  end

  def done?
    self.column.name == 'Done' || self.column.id == 0
  rescue
    false
  end

  def link
    "#{self.project.link}/issues/#{self.gitlab_internal_id.gsub('#','')}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:gitlab]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.username = auth.info.username
      user.avatar_url = auth.info.image
      user.is_admin = auth.is_admin
      user.state = auth.state
      user.password = Devise.friendly_token[0,20]
      user.scroll_hint = true
    end
  end

  def setup_complete?
    !(self.token.nil? || self.token.empty?)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @no_footer = true
    @show_search = true
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to @board, notice: 'Board was successfully created.'
    else
      render :new
    end
  end

  def update
    if @board.update(board_params)
      redirect_to @board, notice: 'Board was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_url, notice: 'Board was successfully destroyed.'
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  after_action :resort, only: [:update]

  def index
    @tasks = Task.all
    @boards = Board.all
    @tasks_unassigned = Task.where(column: nil)
    @tasks_closed = Task.where(column: 0)

    @grouped_options = Board.all.map{|b| [b.name, b.columns.map{|c| [c.name, c.id]}]}
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      unless request.xhr?
        redirect_back fallback_location: :tasks
      else
        broadcast_notification @task, current_user
        render json: @task
      end
      gitlab = Gitlab.new(api_url: ENV['API_URL'], token: current_user.token)
      gitlab.update_gitlab_issue(@task)
    else
      render(:edit) unless request.xhr?
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def broadcast_notification(task, user)
      source = if task.column_id_previous_change
                 Column.find(task.column_id_previous_change.first)
               elsif task.column
                 task.column
               else
                 nil
               end
      ActionCable.server.broadcast(
        'notifications',
        dom_id: "##{task.id}",
        name: task.title,
        source: source.name,
        destination: task.column.name,
        user: user.name
      )
    end

    def task_params
      p = params.require(:task).permit(:milestone_id, :assignee_id, :title,
                                       :link, :gitlab_id, :project_id, :state,
                                       :labels, :due_date, :position,
                                       :comments_id, :column_id,
                                       :is_acknowledged)
      if p[:column_id] && p[:column_id].empty?
        p[:column_id] = nil
      elsif p[:column_id]
        p[:column_id] = p[:column_id].to_i
      end
      p
    end

    def resort
      return unless params[:positions]
      Task.transaction do
        params[:positions].each do |col, el|
          el.each_with_index do |e, i|
            Task.find(e).update position: i
          end
        end
      end
      ActionCable.server.broadcast('boards', task: @task)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user

    @new_filter = Filter.new
    @filter_types = Filter::TYPES
    @filters = Filter.all

    @grouped_options = Board.all.map{|b| [b.name, b.columns.map{|c| [c.name, c.id]}]}
  end

  def update
    current_user.update(user_params)
    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:token, :show_scroll_hint)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    'active' if current_page?(path)
  end
end

app/helpers/assignees_helper.rb
module AssigneesHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/filter_helper.rb
module FilterHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_filter.html.haml
%h5 Filter
.grey-text
  Filters will move unassigned task into the target column if the regexp matches
%hr
.col.s12
  = form_for @new_filter do |f|
    %table
      %thead
        %tr
          %th Type
          %th Match
          %th Target
          %th
      %tbody
        - @filters.each do |filter|
          %tr
            %td= filter.type
            %td= filter.match
            %td= filter.column.name
            %td
              = link_to filter_path(filter), method: :delete do
                .btn-floating.red
                  %i.fa.fa-trash
        %tr
          %td
            .input-field
              = f.select :type, @filter_types
          %td
            .input-field
              = f.label :match
              = f.text_field :match
          %td
            .input-field
              = f.select :column_id, grouped_options_for_select(@grouped_options)
          %td
            = f.button class: 'btn-floating yellow darken-4' do
              %i.fa.fa-plus

app/views/users/show.html.haml
.container
  - if @user.is_admin
    .row
      .card-panel.grey.lighten-5
        .row
          .col.s5
            .row.valign-wrapper
              .col.s2.black-text
                %i.fa.fa-3x.fa-cogs
              .col.s10
                %span.black-text
                  %h4 Global Settings
          .col.s7
            .row.black-text
              = render partial: 'filter'
  .row
    = form_for(@user) do |f|
      .card-panel.grey.lighten-5
        .row
          .col.s6
            .row.valign-wrapper
              .col.s2
                %img.circle.responsive-img{src: @user.avatar_url}
              .col.s10
                %span.black-text
                  %h4= @user.name
          .col.s6.black-text
            .row
              %h5 Basic
              %hr
            .row
              .input-field.col-s12
                %i.fa.fa-key.prefix
                = f.text_field :token, class: 'validate'
                = f.label(:token, 'Token')
            .row
              %h5 Advanced
              %hr
              .input-field.col-s12
                = f.check_box :show_scroll_hint
                = f.label(:show_scroll_hint)
              .input-field.col-s12
                = f.check_box :is_admin, disabled: true
                = f.label(:is_admin)
            .row
              = f.submit 'Submit', class: 'btn yellow darken-4 pull-right'
  .row
    .card-panel.grey.lighten-5.black-text
      .row
        %h5 About Gitban
        %hr
        %ul.collection
          %li.collection-item
            Version
            .secondary-content=Rails.configuration.version
          %li.collection-item
            Environment
            .secondary-content= Rails.env