config/routes.rb
Rails.application.routes.draw do
  resources :columns
  resources :boards
  resources :projects
  resources :assignees
  resources :milestones
  resources :tasks
  resources :filters

  root to: 'welcome#index'

  mount ActionCable.server => '/cable'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  get 'users/:id', to: 'users#show', as: :user
  patch 'users/:id', to: 'users#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignee.rb
class Assignee < ApplicationRecord
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :columns
end

app/models/column.rb
class Column < ApplicationRecord
  default_scope { order(:position) }

  belongs_to :board

  has_many :tasks

  validates :name, presence: true
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :column

  Filter.inheritance_column = '_type'

  TYPES = ['namespace', 'project', 'title']
end

app/models/milestone.rb
class Milestone < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :milestone, optional: true
  belongs_to :assignee, optional: true
  belongs_to :project, optional: true
  belongs_to :column, optional: true

  self.inheritance_column = :_type_disabled

  serialize :labels

  default_scope { order(:position) }

  def in_progress?
    !!['Testing', 'In Progress'].include?(self.column.name)
  rescue
    false
  end

  def done?
    self.column.name == 'Done' || self.column.id == 0
  rescue
    false
  end

  def link
    "#{self.project.link}/issues/#{self.gitlab_internal_id.gsub('#','')}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:gitlab]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.username = auth.info.username
      user.avatar_url = auth.info.image
      user.is_admin = auth.is_admin
      user.state = auth.state
      user.password = Devise.friendly_token[0,20]
      user.scroll_hint = true
    end
  end

  def setup_complete?
    !(self.token.nil? || self.token.empty?)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @no_footer = true
    @show_search = true
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to @board, notice: 'Board was successfully created.'
    else
      render :new
    end
  end

  def update
    if @board.update(board_params)
      redirect_to @board, notice: 'Board was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_url, notice: 'Board was successfully destroyed.'
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: [:show, :edit, :update, :destroy]

  def index
    @columns = Column.all
  end

  def show
  end

  def new
    @column = Column.new
  end

  def edit
  end

  def create
    @column = Column.new(column_params)

    if @column.save
      redirect_to @column, notice: 'Column was successfully created.'
    else
      render :new
    end
  end

  def update
    if @column.update(column_params)
      redirect_to @column, notice: 'Column was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @column.destroy
    redirect_to columns_url, notice: 'Column was successfully destroyed.'
  end

  private
    def set_column
      @column = Column.find(params[:id])
    end

    def column_params
      params.require(:column).permit(:name, :min, :max, :board_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  after_action :resort, only: [:update]

  def index
    @tasks = Task.all
    @boards = Board.all
    @tasks_unassigned = Task.where(column: nil)
    @tasks_closed = Task.where(column: 0)

    @grouped_options = Board.all.map{|b| [b.name, b.columns.map{|c| [c.name, c.id]}]}
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      unless request.xhr?
        redirect_back fallback_location: :tasks
      else
        broadcast_notification @task, current_user
        render json: @task
      end
      gitlab = Gitlab.new(api_url: ENV['API_URL'], token: current_user.token)
      gitlab.update_gitlab_issue(@task)
    else
      render(:edit) unless request.xhr?
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def broadcast_notification(task, user)
      source = if task.column_id_previous_change
                 Column.find(task.column_id_previous_change.first)
               elsif task.column
                 task.column
               else
                 nil
               end
      ActionCable.server.broadcast(
        'notifications',
        dom_id: "##{task.id}",
        name: task.title,
        source: source.name,
        destination: task.column.name,
        user: user.name
      )
    end

    def task_params
      p = params.require(:task).permit(:milestone_id, :assignee_id, :title,
                                       :link, :gitlab_id, :project_id, :state,
                                       :labels, :due_date, :position,
                                       :comments_id, :column_id,
                                       :is_acknowledged)
      if p[:column_id] && p[:column_id].empty?
        p[:column_id] = nil
      elsif p[:column_id]
        p[:column_id] = p[:column_id].to_i
      end
      p
    end

    def resort
      return unless params[:positions]
      Task.transaction do
        params[:positions].each do |col, el|
          el.each_with_index do |e, i|
            Task.find(e).update position: i
          end
        end
      end
      ActionCable.server.broadcast('boards', task: @task)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user

    @new_filter = Filter.new
    @filter_types = Filter::TYPES
    @filters = Filter.all

    @grouped_options = Board.all.map{|b| [b.name, b.columns.map{|c| [c.name, c.id]}]}
  end

  def update
    current_user.update(user_params)
    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:token, :show_scroll_hint)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    'active' if current_page?(path)
  end
end

app/helpers/assignees_helper.rb
module AssigneesHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/filter_helper.rb
module FilterHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/columns/_form.html.haml
= form_for(column) do |f|
  - if column.errors.any?
    #error_explanation
      %h2
        = pluralize(column.errors.count, "error")
        prohibited this column from being saved:
      %ul
        - column.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :min
    = f.number_field :min
  .field
    = f.label :max
    = f.number_field :max
  .field
    = f.label :board_id
    = f.text_field :board_id
  .actions
    = f.submit class: 'btn yellow darken-4'

app/views/columns/edit.html.haml
.container
  %h1 Editing Column
  = render 'form', column: @column
  = link_to 'Back', columns_path, class: 'btn red'

app/views/columns/index.html.haml
%p#notice= notice
.container
  %h1 Columns
  %table.white-text
    %thead
      %tr
        %th Name
        %th Min
        %th Max
        %th Board
        %th
    %tbody
      - @columns.each do |column|
        %tr
          %td= column.name
          %td= column.min
          %td= column.max
          %td
            - b_id = column.board.id
            = link_to "Board #{b_id}", column.board, class: 'btn grey darken-4'
          %td.right-align
            = link_to 'Edit', edit_column_path(column), class: 'btn yellow darken-4'
            = link_to 'Destroy', column, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn red'
  = link_to 'New Column', new_column_path, class: 'btn green'

app/views/columns/new.html.haml
.container
  %h1 New Column
  = render 'form', column: @column
  = link_to 'Back', columns_path, class: 'btn'

app/views/tasks/_form.html.haml
= form_for(task) do |f|
  - if task.errors.any?
    #error_explanation
      %h2
        = pluralize(task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - task.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :milestone_id
    = f.text_field :milestone_id
  .field
    = f.label :assignee_id
    = f.text_field :assignee_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :gitlab_id
    = f.number_field :gitlab_id
  .field
    = f.label :project_id
    = f.text_field :project_id
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :labels
    = f.text_field :labels
  .field
    = f.label :due_date
    = f.date_select :due_date
  .field
    = f.label :position
    = f.text_field :position
  .field
    = f.label :column_id
    = f.text_field :column_id
  .actions
    = f.submit class: :btn

app/views/tasks/edit.html.haml
.container
  %h1 Editing Task
  = render 'form', task: @task
  = link_to 'Show', @task
  |
  = link_to 'Back', tasks_path

app/views/tasks/index.html.haml
.page-header
  %h3.text-muted Tasks that are not assigned to any board are listed here
%p
  These tasks seemed to be newly imported from GitLab;
  or you just decided to remove them from your board.
%p
  However, you can - and should - reassign them to a existing board.
.containter
  .col.s12
    %ul.tabs
      %li.tab.col.s6
        %a.blue-text.text-darken-2.active{href: '#unassigned'} Unassigned
      %li.tab.col.s6
        %a.blue-text.text-darken-2{href: '#closed'} Closed
  .col.s12#unassigned
    - @tasks_unassigned.each_slice(4) do |tasks|
      .row
        - tasks.each do |task|
          .col.s3
            = render partial: 'shared/task_card', locals: {task: task, animate: 0}
  .col.s12#closed{style: 'height: 100%;'}
    - @tasks_closed.each_slice(4) do |tasks|
      .row
        - tasks.each do |task|
          .col.s3
            = render partial: 'shared/task_card', locals: {task: task, animate: 0}

app/views/tasks/new.html.haml
.container
  %h1 New Task
  = render 'form', task: @task
  = link_to 'Back', tasks_path

app/views/tasks/show.html.haml
.container
  %p#notice= notice
  %p
    %strong Milestone:
    = @task.milestone
  %p
    %strong Assignee:
    = @task.assignee
  %p
    %strong Title:
    = @task.title
  %p
    %strong Link:
    = @task.link
  %p
    %strong Gitlabid:
    = @task.gitlab_id
  %p
    %strong Project:
    = @task.project
  %p
    %strong State:
    = @task.state
  %p
    %strong Labels:
    = @task.labels
  %p
    %strong Due date:
    = @task.due_date
  %p
    %strong Position:
    = @task.position
  %p
    %strong Column:
    = @task.column
  = link_to 'Edit', edit_task_path(@task)
  |
  = link_to 'Back', tasks_path